version: "3"
services:
  db:
    image: mysql:latest
    container_name: local-mysql-simple-forum
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=fastcampus
    volumes:
      - D:\Developments\dbdocker\FastCampus\simple-forum:/var/lib/mysql
